// helpers/csvExport.js
import dayjs from "dayjs";
import { authStore } from "../store/authStore";
import { downloadCsv } from "./download";

const auth = authStore;

/* ---------------- CSV Export ---------------- */
export async function csvExport({ headers = [], rows = [], title = "Report", fileName = "export.csv" } = {}) {
  try {
    const orgName = auth?.user?.org_name ?? "Azonation";
    const today = dayjs().format("DD MMM YYYY");

    // Normalize headers
    const normalizedHeaders = headers.map(h => ({
      text: h.text ?? h.label ?? String(h.value ?? ""),
      value: h.value ?? h.key ?? String(h.text ?? ""),
    }));

    const headerLabels = normalizedHeaders.map(h => h.text);

    // Prepare data rows
    const dataRows = rows.map(item =>
      normalizedHeaders.map(h => {
        if (typeof h.value === "function") {
          try { return h.value(item); } catch { return ""; }
        }
        return item[h.value] ?? item[h.text] ?? "";
      })
    );

    const footerText = `Generated by Azonation on ${today} | Items 1–${rows?.length ?? 0} of ${rows?.length ?? 0} | Page 1 of 1`;

    downloadCsv(
      [
        [], // empty row on top
        [orgName],
        [title],
        [], // empty row before table
        headerLabels,
        ...dataRows,
        [],
        [footerText],
      ],
      fileName,
    );
  } catch (err) {
    console.error("csvExport error:", err);
    throw err;
  }
}
